# Generated by Django 5.2 on 2025-11-13 00:58

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Bill",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now, editable=False
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "name",
                    models.CharField(
                        help_text="Bill name (e.g., 'Rent', 'Electricity', 'Internet')",
                        max_length=255,
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, help_text="Optional bill description"),
                ),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2, help_text="Bill amount", max_digits=12
                    ),
                ),
                ("due_date", models.DateField(help_text="When this bill is due")),
                (
                    "frequency",
                    models.CharField(
                        choices=[
                            ("weekly", "Weekly"),
                            ("fortnightly", "Fortnightly"),
                            ("monthly", "Monthly"),
                            ("quarterly", "Quarterly"),
                            ("yearly", "Yearly"),
                            ("one_time", "One Time"),
                        ],
                        default="monthly",
                        help_text="How often this bill recurs",
                        max_length=20,
                    ),
                ),
                (
                    "is_recurring",
                    models.BooleanField(
                        default=True, help_text="Whether this bill repeats"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("paid", "Paid"),
                            ("overdue", "Overdue"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="pending",
                        help_text="Current bill status",
                        max_length=20,
                    ),
                ),
                (
                    "paid_date",
                    models.DateField(
                        blank=True, help_text="When this bill was paid", null=True
                    ),
                ),
                (
                    "reminder_days_before",
                    models.PositiveIntegerField(
                        default=3, help_text="Days before due date to send reminder"
                    ),
                ),
                (
                    "auto_pay_enabled",
                    models.BooleanField(
                        default=False,
                        help_text="Whether this bill is set up for automatic payment",
                    ),
                ),
                (
                    "color",
                    models.CharField(
                        default="#EF4444",
                        help_text="Hex color for UI display",
                        max_length=7,
                    ),
                ),
                (
                    "notes",
                    models.TextField(
                        blank=True, help_text="Additional notes about this bill"
                    ),
                ),
                (
                    "account",
                    models.ForeignKey(
                        blank=True,
                        help_text="Account used to pay this bill",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="bills",
                        to="accounts.account",
                    ),
                ),
            ],
            options={
                "verbose_name": "Bill",
                "verbose_name_plural": "Bills",
                "db_table": "bills",
                "ordering": ["due_date", "name"],
            },
        ),
    ]
