# Generated by Django 5.2 on 2025-11-16 20:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("bills", "0001_initial"),
        ("categories", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="bill",
            name="category",
            field=models.ForeignKey(
                blank=True,
                help_text="Category for this bill",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="bills",
                to="categories.category",
            ),
        ),
    ]
