# Generated by Django 5.2 on 2025-11-13 00:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("bills", "0002_initial"),
        ("households", "0001_initial"),
        ("transactions", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="bill",
            name="household",
            field=models.ForeignKey(
                help_text="Household this bill belongs to",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="bills",
                to="households.household",
            ),
        ),
        migrations.AddField(
            model_name="bill",
            name="next_bill",
            field=models.ForeignKey(
                blank=True,
                help_text="Next instance of this recurring bill",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="previous_bill",
                to="bills.bill",
            ),
        ),
        migrations.AddField(
            model_name="bill",
            name="transaction",
            field=models.ForeignKey(
                blank=True,
                help_text="Transaction that paid this bill",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="bills",
                to="transactions.transaction",
            ),
        ),
        migrations.AddIndex(
            model_name="bill",
            index=models.Index(
                fields=["household", "due_date"], name="bills_househo_8d0b66_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="bill",
            index=models.Index(
                fields=["household", "status"], name="bills_househo_3bb0d8_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="bill",
            index=models.Index(
                fields=["status", "due_date"], name="bills_status_2d6121_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="bill",
            index=models.Index(fields=["due_date"], name="bills_due_dat_7854b3_idx"),
        ),
    ]
