# Generated by Django 5.2 on 2025-11-17 01:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("bills", "0002_initial"),
        ("households", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="bill",
            name="household",
            field=models.ForeignKey(
                help_text="Household this bill belongs to",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="bills",
                to="households.household",
            ),
        ),
        migrations.AddField(
            model_name="bill",
            name="next_bill",
            field=models.ForeignKey(
                blank=True,
                help_text="Next instance of this recurring bill",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="previous_bill",
                to="bills.bill",
            ),
        ),
    ]
