# Generated by Django 5.2 on 2025-11-16 20:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("bills", "0003_initial"),
        ("transactions", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="bill",
            name="transaction",
            field=models.ForeignKey(
                blank=True,
                help_text="Transaction that paid this bill",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="bills",
                to="transactions.transaction",
            ),
        ),
        migrations.AddField(
            model_name="billattachment",
            name="bill",
            field=models.ForeignKey(
                help_text="Bill this attachment belongs to",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="attachments",
                to="bills.bill",
            ),
        ),
    ]
