# Generated by Django 5.2 on 2025-11-16 20:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("bills", "0004_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="billattachment",
            name="uploaded_by",
            field=models.ForeignKey(
                help_text="User who uploaded this bill",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="uploaded_bills",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddIndex(
            model_name="bill",
            index=models.Index(
                fields=["household", "due_date"], name="bills_househo_8d0b66_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="bill",
            index=models.Index(
                fields=["household", "status"], name="bills_househo_3bb0d8_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="bill",
            index=models.Index(
                fields=["status", "due_date"], name="bills_status_2d6121_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="bill",
            index=models.Index(fields=["due_date"], name="bills_due_dat_7854b3_idx"),
        ),
        migrations.AddIndex(
            model_name="billattachment",
            index=models.Index(
                fields=["bill", "created_at"], name="bill_attach_bill_id_6e4f05_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="billattachment",
            index=models.Index(
                fields=["ocr_processed", "created_at"],
                name="bill_attach_ocr_pro_b3bd7a_idx",
            ),
        ),
    ]
