# Generated by Django 5.2 on 2025-11-17 04:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bills", "0005_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="billattachment",
            name="file",
            field=models.FileField(
                help_text="Bill or invoice document", upload_to="bills/user_%s/%%Y/%%m/"
            ),
        ),
    ]
