# Generated by Django 5.2 on 2025-11-16 20:04

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Alert",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now, editable=False
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "alert_type",
                    models.CharField(
                        choices=[
                            ("budget_warning", "Budget Warning"),
                            ("budget_exceeded", "Budget Exceeded"),
                            ("bill_due", "Bill Due Soon"),
                            ("bill_overdue", "Bill Overdue"),
                            ("goal_milestone", "Goal Milestone Reached"),
                            ("low_balance", "Low Account Balance"),
                            ("unusual_spending", "Unusual Spending Detected"),
                            ("recurring_transaction", "Recurring Transaction Reminder"),
                            ("custom", "Custom Alert"),
                        ],
                        help_text="Type of alert",
                        max_length=30,
                    ),
                ),
                (
                    "priority",
                    models.CharField(
                        choices=[
                            ("low", "Low"),
                            ("medium", "Medium"),
                            ("high", "High"),
                            ("urgent", "Urgent"),
                        ],
                        default="medium",
                        help_text="Alert priority level",
                        max_length=10,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("dismissed", "Dismissed"),
                            ("resolved", "Resolved"),
                        ],
                        default="active",
                        help_text="Current alert status",
                        max_length=20,
                    ),
                ),
                (
                    "message",
                    models.TextField(help_text="Alert message displayed to user"),
                ),
                (
                    "title",
                    models.CharField(
                        blank=True, help_text="Optional alert title", max_length=255
                    ),
                ),
                (
                    "trigger_value",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Threshold value that triggered this alert (e.g., budget %, balance amount)",
                        max_digits=12,
                        null=True,
                    ),
                ),
                (
                    "action_required",
                    models.BooleanField(
                        default=False,
                        help_text="Whether this alert requires user action",
                    ),
                ),
                (
                    "action_url",
                    models.URLField(
                        blank=True,
                        help_text="Optional URL for alert action (e.g., link to budget page)",
                    ),
                ),
                (
                    "sent_via_email",
                    models.BooleanField(
                        default=False, help_text="Whether this alert was sent via email"
                    ),
                ),
                (
                    "sent_via_push",
                    models.BooleanField(
                        default=False,
                        help_text="Whether this alert was sent via push notification",
                    ),
                ),
                (
                    "dismissed_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="When user dismissed this alert",
                        null=True,
                    ),
                ),
            ],
            options={
                "verbose_name": "Alert",
                "verbose_name_plural": "Alerts",
                "db_table": "alerts",
                "ordering": ["-created_at", "-priority"],
            },
        ),
    ]
