# Generated by Django 5.2 on 2025-11-13 00:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("accounts", "0002_initial"),
        ("alerts", "0001_initial"),
        ("bills", "0003_initial"),
        ("budgets", "0002_initial"),
        ("goals", "0002_initial"),
        ("households", "0002_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="alert",
            name="dismissed_by",
            field=models.ForeignKey(
                blank=True,
                help_text="User who dismissed this alert",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="dismissed_alerts",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="alert",
            name="household",
            field=models.ForeignKey(
                help_text="Household this alert belongs to",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="alerts",
                to="households.household",
            ),
        ),
        migrations.AddField(
            model_name="alert",
            name="related_account",
            field=models.ForeignKey(
                blank=True,
                help_text="Account that triggered this alert (if applicable)",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="alerts",
                to="accounts.account",
            ),
        ),
        migrations.AddField(
            model_name="alert",
            name="related_bill",
            field=models.ForeignKey(
                blank=True,
                help_text="Bill that triggered this alert (if applicable)",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="alerts",
                to="bills.bill",
            ),
        ),
        migrations.AddField(
            model_name="alert",
            name="related_budget",
            field=models.ForeignKey(
                blank=True,
                help_text="Budget that triggered this alert (if applicable)",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="alerts",
                to="budgets.budget",
            ),
        ),
        migrations.AddField(
            model_name="alert",
            name="related_goal",
            field=models.ForeignKey(
                blank=True,
                help_text="Goal that triggered this alert (if applicable)",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="alerts",
                to="goals.goal",
            ),
        ),
        migrations.AddIndex(
            model_name="alert",
            index=models.Index(
                fields=["household", "status", "created_at"],
                name="alerts_househo_2eee9d_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="alert",
            index=models.Index(
                fields=["household", "alert_type"], name="alerts_househo_4bbcc4_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="alert",
            index=models.Index(
                fields=["status", "created_at"], name="alerts_status_dc9bed_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="alert",
            index=models.Index(
                fields=["priority", "status"], name="alerts_priorit_d3d1b2_idx"
            ),
        ),
    ]
