# Generated by Django 5.2 on 2025-11-17 01:20

import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Account",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now, editable=False
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "uuid",
                    models.UUIDField(
                        db_index=True,
                        default=uuid.uuid4,
                        editable=False,
                        help_text="Unique identifier for API and bank integrations",
                        unique=True,
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                (
                    "institution",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Bank or provider name (optional)",
                        max_length=255,
                    ),
                ),
                (
                    "account_type",
                    models.CharField(
                        choices=[
                            ("checking", "Checking Account"),
                            ("savings", "Savings Account"),
                            ("credit", "Credit Card"),
                            ("cash", "Cash"),
                            ("investment", "Investment Account"),
                            ("other", "Other"),
                        ],
                        default="checking",
                        max_length=20,
                    ),
                ),
                (
                    "currency",
                    models.CharField(
                        default="NZD",
                        help_text="Store ISO currency code",
                        max_length=10,
                    ),
                ),
                (
                    "include_in_totals",
                    models.BooleanField(
                        default=True,
                        help_text="Whether to include this account in balance summaries",
                    ),
                ),
                (
                    "balance",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "available_credit",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="For credit accounts",
                        max_digits=12,
                        null=True,
                    ),
                ),
                (
                    "credit_limit",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="For credit accounts",
                        max_digits=12,
                        null=True,
                    ),
                ),
            ],
            options={
                "verbose_name": "Account",
                "verbose_name_plural": "Accounts",
                "db_table": "accounts",
            },
        ),
    ]
