# Generated by Django 5.2 on 2025-11-13 00:58

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Account",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now, editable=False
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "account_name",
                    models.CharField(
                        help_text="Descriptive name for the account (e.g., 'ANZ Everyday', 'Emergency Cash')",
                        max_length=255,
                    ),
                ),
                (
                    "account_type",
                    models.CharField(
                        choices=[
                            ("checking", "Checking Account"),
                            ("savings", "Savings Account"),
                            ("credit", "Credit Card"),
                            ("cash", "Cash"),
                            ("investment", "Investment Account"),
                            ("other", "Other"),
                        ],
                        default="checking",
                        help_text="Type of account",
                        max_length=20,
                    ),
                ),
                (
                    "opening_balance",
                    models.DecimalField(
                        decimal_places=2,
                        default=0.0,
                        help_text="Initial balance when account was added to system",
                        max_digits=12,
                    ),
                ),
                (
                    "balance",
                    models.DecimalField(
                        decimal_places=2,
                        default=0.0,
                        help_text="Current account balance (updated via transaction service)",
                        max_digits=12,
                    ),
                ),
                (
                    "institution_name",
                    models.CharField(
                        blank=True,
                        help_text="Bank or financial institution name (e.g., 'ANZ', 'Westpac')",
                        max_length=255,
                    ),
                ),
                (
                    "account_number",
                    models.CharField(
                        blank=True,
                        help_text="Last 4 digits or masked account number for reference",
                        max_length=50,
                    ),
                ),
                (
                    "credit_limit",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Credit limit for credit card accounts",
                        max_digits=12,
                        null=True,
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Whether this account is currently active",
                    ),
                ),
                (
                    "currency",
                    models.CharField(
                        default="NZD",
                        help_text="Currency code (NZD, AUD, USD, etc.)",
                        max_length=3,
                    ),
                ),
                (
                    "include_in_totals",
                    models.BooleanField(
                        default=True,
                        help_text="Whether to include this account in household total calculations",
                    ),
                ),
            ],
            options={
                "verbose_name": "Account",
                "verbose_name_plural": "Accounts",
                "db_table": "accounts",
                "ordering": ["-is_active", "account_name"],
            },
        ),
    ]
