# Generated by Django 5.2 on 2025-11-16 20:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("accounts", "0001_initial"),
        ("households", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="account",
            name="household",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="accounts",
                to="households.household",
            ),
        ),
        migrations.AddIndex(
            model_name="account",
            index=models.Index(fields=["uuid"], name="accounts_uuid_162a7f_idx"),
        ),
        migrations.AddIndex(
            model_name="account",
            index=models.Index(
                fields=["household", "account_type"], name="accounts_househo_169d7e_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="account",
            index=models.Index(
                fields=["household", "include_in_totals"],
                name="accounts_househo_91038e_idx",
            ),
        ),
    ]
