# Generated by Django 5.2 on 2025-11-13 00:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("accounts", "0001_initial"),
        ("households", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="account",
            name="household",
            field=models.ForeignKey(
                help_text="Household this account belongs to",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="accounts",
                to="households.household",
            ),
        ),
        migrations.AddIndex(
            model_name="account",
            index=models.Index(
                fields=["household", "is_active"], name="accounts_househo_8c1dbf_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="account",
            index=models.Index(
                fields=["household", "account_type"], name="accounts_househo_169d7e_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="account",
            unique_together={("household", "account_name")},
        ),
    ]
