# Generated by Django 5.2 on 2025-11-14 00:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="account",
            name="name",
            field=models.CharField(default="Untitled Account", max_length=255),
        ),
    ]
