# Generated by Django 5.2 on 2025-11-14 00:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0003_account_name"),
        (
            "households",
            "0004_remove_membership_memberships_user_id_b0e170_idx_and_more",
        ),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="account",
            options={"verbose_name": "Account", "verbose_name_plural": "Accounts"},
        ),
        migrations.RemoveIndex(
            model_name="account",
            name="accounts_househo_8c1dbf_idx",
        ),
        migrations.AlterUniqueTogether(
            name="account",
            unique_together=set(),
        ),
        migrations.AddField(
            model_name="account",
            name="available_credit",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="For credit accounts",
                max_digits=12,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="account",
            name="institution",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Bank or provider name (optional)",
                max_length=255,
            ),
        ),
        migrations.AlterField(
            model_name="account",
            name="account_type",
            field=models.CharField(
                choices=[
                    ("checking", "Checking Account"),
                    ("savings", "Savings Account"),
                    ("credit", "Credit Card"),
                    ("cash", "Cash"),
                    ("investment", "Investment Account"),
                    ("other", "Other"),
                ],
                default="checking",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="account",
            name="balance",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AlterField(
            model_name="account",
            name="credit_limit",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="For credit accounts",
                max_digits=12,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="account",
            name="currency",
            field=models.CharField(
                default="NZD", help_text="Store ISO currency code", max_length=10
            ),
        ),
        migrations.AlterField(
            model_name="account",
            name="household",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="accounts",
                to="households.household",
            ),
        ),
        migrations.AlterField(
            model_name="account",
            name="include_in_totals",
            field=models.BooleanField(
                default=True,
                help_text="Whether to include this account in balance summaries",
            ),
        ),
        migrations.AlterField(
            model_name="account",
            name="name",
            field=models.CharField(max_length=255),
        ),
        migrations.AddIndex(
            model_name="account",
            index=models.Index(
                fields=["household", "include_in_totals"],
                name="accounts_househo_91038e_idx",
            ),
        ),
        migrations.RemoveField(
            model_name="account",
            name="account_name",
        ),
        migrations.RemoveField(
            model_name="account",
            name="account_number",
        ),
        migrations.RemoveField(
            model_name="account",
            name="institution_name",
        ),
        migrations.RemoveField(
            model_name="account",
            name="is_active",
        ),
        migrations.RemoveField(
            model_name="account",
            name="opening_balance",
        ),
    ]
