# Generated by Django 5.2 on 2025-11-16 10:49

import uuid
from django.db import migrations, models


def generate_uuids(apps, schema_editor):
    """Generate unique UUIDs for all existing accounts."""
    account_model = apps.get_model("accounts", "Account")
    for account in account_model.objects.all():
        account.uuid = uuid.uuid4()
        account.save(update_fields=["uuid"])


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0004_alter_account_options_and_more"),
        ("households", "0005_add_uuid_field"),
    ]

    operations = [
        # Step 1: Add uuid field as nullable and non-unique
        migrations.AddField(
            model_name="account",
            name="uuid",
            field=models.UUIDField(
                db_index=True,
                editable=False,
                help_text="Unique identifier for API and bank integrations",
                null=True,
                blank=True,
            ),
        ),
        # Step 2: Generate UUIDs for existing records
        migrations.RunPython(generate_uuids),
        # Step 3: Make uuid field non-nullable and unique
        migrations.AlterField(
            model_name="account",
            name="uuid",
            field=models.UUIDField(
                db_index=True,
                default=uuid.uuid4,
                editable=False,
                help_text="Unique identifier for API and bank integrations",
                unique=True,
            ),
        ),
        # Step 4: Add index
        migrations.AddIndex(
            model_name="account",
            index=models.Index(fields=["uuid"], name="accounts_uuid_162a7f_idx"),
        ),
    ]
