# Generated by Django 5.2 on 2025-11-16 20:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("categories", "0001_initial"),
        ("households", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="category",
            name="household",
            field=models.ForeignKey(
                blank=True,
                help_text="Household this category belongs to",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="categories",
                to="households.household",
            ),
        ),
        migrations.AddField(
            model_name="category",
            name="parent",
            field=models.ForeignKey(
                blank=True,
                help_text="Parent category (for hierarchical organization)",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="subcategories",
                to="categories.category",
            ),
        ),
        migrations.AddIndex(
            model_name="category",
            index=models.Index(
                fields=["household", "is_active", "is_deleted"],
                name="categories_househo_496b11_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="category",
            index=models.Index(
                fields=["household", "category_type", "is_deleted"],
                name="categories_househo_aa87d0_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="category",
            index=models.Index(fields=["parent"], name="categories_parent__7983b2_idx"),
        ),
        migrations.AddIndex(
            model_name="category",
            index=models.Index(
                fields=["is_system"], name="categories_is_syst_2704b6_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="category",
            unique_together={("household", "name", "is_deleted")},
        ),
    ]
