# Generated by Django 5.2 on 2025-11-16 10:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("categories", "0002_initial"),
        (
            "households",
            "0004_remove_membership_memberships_user_id_b0e170_idx_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="category",
            name="household",
            field=models.ForeignKey(
                blank=True,
                help_text="Household this category belongs to",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="categories",
                to="households.household",
            ),
        ),
    ]
