"""
Enhanced Security Headers Middleware
Generated by security fix script
"""


class SecurityHeadersMiddleware:
    """Enforce security headers on all responses"""

    def __init__(self, get_response):
        self.get_response = get_response

    def __call__(self, request):
        response = self.get_response(request)

        # Remove server version
        if "Server" in response:
            del response["Server"]

        # Prevent MIME-sniffing
        response["X-Content-Type-Options"] = "nosniff"

        # Strict referrer policy
        response["Referrer-Policy"] = "strict-origin-when-cross-origin"

        # Permissions policy
        response["Permissions-Policy"] = (
            "geolocation=(), microphone=(), camera=(),payment=(), usb=()"
        )

        return response


class CookieSecurityMiddleware:
    """Enforce secure cookie attributes"""

    def __init__(self, get_response):
        self.get_response = get_response

    def __call__(self, request):
        response = self.get_response(request)

        # Ensure HttpOnly and SameSite on cookies
        if hasattr(response, "cookies") and response.cookies:
            for cookie_name in response.cookies:
                morsel = response.cookies[cookie_name]
                if cookie_name in ("sessionid", "csrftoken"):
                    morsel["httponly"] = True
                if not morsel.get("samesite"):
                    morsel["samesite"] = "Strict"

        return response
