# Generated by Django 5.2 on 2025-11-13 00:58

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("accounts", "0001_initial"),
        ("budgets", "0001_initial"),
        ("categories", "0001_initial"),
        ("goals", "0001_initial"),
        ("households", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="TransactionTag",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now, editable=False
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(help_text="Tag name", max_length=50)),
                (
                    "color",
                    models.CharField(
                        default="#6B7280",
                        help_text="Hex color for UI display (e.g., '#FF5733')",
                        max_length=7,
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True, help_text="Optional description of tag usage"
                    ),
                ),
                (
                    "household",
                    models.ForeignKey(
                        help_text="Household this tag belongs to",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="transaction_tags",
                        to="households.household",
                    ),
                ),
            ],
            options={
                "verbose_name": "Transaction Tag",
                "verbose_name_plural": "Transaction Tags",
                "db_table": "transaction_tags",
                "ordering": ["name"],
                "unique_together": {("household", "name")},
            },
        ),
        migrations.CreateModel(
            name="Transaction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now, editable=False
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "transaction_type",
                    models.CharField(
                        choices=[
                            ("income", "Income"),
                            ("expense", "Expense"),
                            ("transfer", "Transfer"),
                        ],
                        help_text="Type of transaction",
                        max_length=20,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="completed",
                        help_text="Current transaction status",
                        max_length=20,
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Transaction amount (positive for income, negative for expense)",
                        max_digits=12,
                    ),
                ),
                (
                    "description",
                    models.CharField(
                        help_text="Transaction description", max_length=500
                    ),
                ),
                (
                    "date",
                    models.DateTimeField(help_text="When the transaction occurred"),
                ),
                (
                    "receipt_image",
                    models.ImageField(
                        blank=True,
                        help_text="Uploaded receipt image (if entered via OCR)",
                        null=True,
                        upload_to="receipts/%Y/%m/",
                    ),
                ),
                (
                    "voice_entry_flag",
                    models.BooleanField(
                        default=False, help_text="Whether this was entered via voice"
                    ),
                ),
                (
                    "transaction_source",
                    models.CharField(
                        choices=[
                            ("manual", "Manual Entry"),
                            ("voice", "Voice Entry"),
                            ("receipt", "Receipt OCR"),
                            ("bank_import", "Bank Import"),
                        ],
                        default="manual",
                        help_text="How this transaction was entered",
                        max_length=20,
                    ),
                ),
                (
                    "merchant",
                    models.CharField(
                        blank=True, help_text="Merchant/vendor name", max_length=255
                    ),
                ),
                ("notes", models.TextField(blank=True, help_text="Additional notes")),
                (
                    "is_recurring",
                    models.BooleanField(
                        default=False,
                        help_text="Whether this is a recurring transaction",
                    ),
                ),
                (
                    "account",
                    models.ForeignKey(
                        help_text="Account this transaction belongs to",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="transactions",
                        to="accounts.account",
                    ),
                ),
                (
                    "budget",
                    models.ForeignKey(
                        blank=True,
                        help_text="Budget this transaction is tracked against",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="transactions",
                        to="budgets.budget",
                    ),
                ),
                (
                    "category",
                    models.ForeignKey(
                        blank=True,
                        help_text="Primary transaction category",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="transactions",
                        to="categories.category",
                    ),
                ),
                (
                    "goal",
                    models.ForeignKey(
                        blank=True,
                        help_text="Goal this transaction contributes to (if applicable)",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="transactions",
                        to="goals.goal",
                    ),
                ),
                (
                    "linked_transaction",
                    models.ForeignKey(
                        blank=True,
                        help_text="Linked transaction for transfers (opposite account)",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="transfer_pair",
                        to="transactions.transaction",
                    ),
                ),
                (
                    "tags",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Additional tags for flexible categorization",
                        related_name="transactions",
                        to="transactions.transactiontag",
                    ),
                ),
            ],
            options={
                "verbose_name": "Transaction",
                "verbose_name_plural": "Transactions",
                "db_table": "transactions",
                "ordering": ["-date", "-created_at"],
                "indexes": [
                    models.Index(
                        fields=["account", "date"],
                        name="transaction_account_f34883_idx",
                    ),
                    models.Index(
                        fields=["category", "date"],
                        name="transaction_categor_3ca96c_idx",
                    ),
                    models.Index(
                        fields=["transaction_type", "status", "date"],
                        name="transaction_transac_b72ca1_idx",
                    ),
                    models.Index(fields=["date"], name="transaction_date_7edf95_idx"),
                    models.Index(
                        fields=["account", "-date"],
                        name="transaction_account_bed7b9_idx",
                    ),
                    models.Index(
                        fields=["status", "date"], name="transaction_status_719ef2_idx"
                    ),
                ],
            },
        ),
    ]
