# Generated by Django 5.2 on 2025-11-16 20:04

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("accounts", "0002_initial"),
        ("budgets", "0002_initial"),
        ("categories", "0002_initial"),
        ("goals", "0002_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="TransactionSplit",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now, editable=False
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Amount for this split portion",
                        max_digits=12,
                    ),
                ),
                (
                    "description",
                    models.CharField(
                        blank=True,
                        help_text="Description for this split portion",
                        max_length=255,
                    ),
                ),
            ],
            options={
                "verbose_name": "Transaction Split",
                "verbose_name_plural": "Transaction Splits",
                "db_table": "transaction_splits",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="TransactionTag",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now, editable=False
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(help_text="Tag name", max_length=50)),
                (
                    "color",
                    models.CharField(
                        default="#6B7280",
                        help_text="Hex color for UI display (e.g., '#FF5733')",
                        max_length=7,
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True, help_text="Optional description of tag usage"
                    ),
                ),
            ],
            options={
                "verbose_name": "Transaction Tag",
                "verbose_name_plural": "Transaction Tags",
                "db_table": "transaction_tags",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Transaction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now, editable=False
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "uuid",
                    models.UUIDField(
                        db_index=True,
                        default=uuid.uuid4,
                        editable=False,
                        help_text="Unique identifier for API, webhooks, and idempotent imports",
                        unique=True,
                    ),
                ),
                (
                    "transaction_type",
                    models.CharField(
                        choices=[
                            ("income", "Income"),
                            ("expense", "Expense"),
                            ("transfer", "Transfer"),
                        ],
                        help_text="Type of transaction",
                        max_length=20,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="completed",
                        help_text="Current transaction status",
                        max_length=20,
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Transaction amount (positive for income, negative for expense)",
                        max_digits=12,
                    ),
                ),
                (
                    "description",
                    models.CharField(
                        help_text="Transaction description", max_length=500
                    ),
                ),
                (
                    "date",
                    models.DateTimeField(help_text="When the transaction occurred"),
                ),
                (
                    "receipt_image",
                    models.ImageField(
                        blank=True,
                        help_text="Uploaded receipt image (if entered via OCR)",
                        null=True,
                        upload_to="receipts/%Y/%m/",
                    ),
                ),
                (
                    "voice_entry_flag",
                    models.BooleanField(
                        default=False, help_text="Whether this was entered via voice"
                    ),
                ),
                (
                    "transaction_source",
                    models.CharField(
                        choices=[
                            ("manual", "Manual Entry"),
                            ("voice", "Voice Entry"),
                            ("receipt", "Receipt OCR"),
                            ("bank_import", "Bank Import"),
                        ],
                        default="manual",
                        help_text="How this transaction was entered",
                        max_length=20,
                    ),
                ),
                (
                    "merchant",
                    models.CharField(
                        blank=True, help_text="Merchant/vendor name", max_length=255
                    ),
                ),
                ("notes", models.TextField(blank=True, help_text="Additional notes")),
                (
                    "is_recurring",
                    models.BooleanField(
                        default=False,
                        help_text="Whether this is a recurring transaction",
                    ),
                ),
                (
                    "account",
                    models.ForeignKey(
                        help_text="Account this transaction belongs to",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="transactions",
                        to="accounts.account",
                    ),
                ),
                (
                    "budget",
                    models.ForeignKey(
                        blank=True,
                        help_text="Budget this transaction is tracked against",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="transactions",
                        to="budgets.budget",
                    ),
                ),
                (
                    "category",
                    models.ForeignKey(
                        blank=True,
                        help_text="Primary transaction category",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="transactions",
                        to="categories.category",
                    ),
                ),
                (
                    "goal",
                    models.ForeignKey(
                        blank=True,
                        help_text="Goal this transaction contributes to (if applicable)",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="transactions",
                        to="goals.goal",
                    ),
                ),
                (
                    "linked_transaction",
                    models.ForeignKey(
                        blank=True,
                        help_text="Linked transaction for transfers (opposite account)",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="transfer_pair",
                        to="transactions.transaction",
                    ),
                ),
            ],
            options={
                "verbose_name": "Transaction",
                "verbose_name_plural": "Transactions",
                "db_table": "transactions",
                "ordering": ["-date", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="TransactionAttachment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now, editable=False
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "file",
                    models.ImageField(
                        help_text="Receipt or invoice image",
                        upload_to="receipts/%Y/%m/",
                    ),
                ),
                (
                    "file_name",
                    models.CharField(help_text="Original filename", max_length=255),
                ),
                ("file_size", models.IntegerField(help_text="File size in bytes")),
                (
                    "file_type",
                    models.CharField(
                        help_text="File extension (jpg, png, pdf)", max_length=10
                    ),
                ),
                (
                    "ocr_processed",
                    models.BooleanField(
                        default=False,
                        help_text="Whether OCR has been run on this image",
                    ),
                ),
                (
                    "ocr_text",
                    models.TextField(blank=True, help_text="Extracted text from OCR"),
                ),
                (
                    "ocr_data",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Structured OCR data (merchant, amount, date, items)",
                    ),
                ),
                (
                    "ocr_confidence",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Average confidence score from OCR (0-100)",
                        max_digits=5,
                        null=True,
                    ),
                ),
                (
                    "ocr_processed_at",
                    models.DateTimeField(
                        blank=True, help_text="When OCR processing completed", null=True
                    ),
                ),
                (
                    "ocr_error",
                    models.TextField(
                        blank=True, help_text="Error message if OCR failed"
                    ),
                ),
                (
                    "transaction",
                    models.ForeignKey(
                        help_text="Transaction this attachment belongs to",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="attachments",
                        to="transactions.transaction",
                    ),
                ),
            ],
            options={
                "verbose_name": "Transaction Attachment",
                "verbose_name_plural": "Transaction Attachments",
                "db_table": "transaction_attachments",
                "ordering": ["-created_at"],
            },
        ),
    ]
