# Generated by Django 5.2 on 2025-11-16 20:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("categories", "0002_initial"),
        ("households", "0003_initial"),
        ("transactions", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="transactionattachment",
            name="uploaded_by",
            field=models.ForeignKey(
                help_text="User who uploaded this receipt",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="uploaded_receipts",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="transactionsplit",
            name="category",
            field=models.ForeignKey(
                blank=True,
                help_text="Category for this portion of the split",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="transaction_splits",
                to="categories.category",
            ),
        ),
        migrations.AddField(
            model_name="transactionsplit",
            name="member",
            field=models.ForeignKey(
                blank=True,
                help_text="Household member responsible for this portion",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="transaction_splits",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="transactionsplit",
            name="transaction",
            field=models.ForeignKey(
                help_text="Parent transaction being split",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="splits",
                to="transactions.transaction",
            ),
        ),
        migrations.AddField(
            model_name="transactiontag",
            name="household",
            field=models.ForeignKey(
                help_text="Household this tag belongs to",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="transaction_tags",
                to="households.household",
            ),
        ),
        migrations.AddField(
            model_name="transaction",
            name="tags",
            field=models.ManyToManyField(
                blank=True,
                help_text="Additional tags for flexible categorization",
                related_name="transactions",
                to="transactions.transactiontag",
            ),
        ),
        migrations.AddIndex(
            model_name="transactionattachment",
            index=models.Index(
                fields=["transaction", "created_at"],
                name="transaction_transac_a379d5_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="transactionattachment",
            index=models.Index(
                fields=["ocr_processed", "created_at"],
                name="transaction_ocr_pro_ad4c48_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="transactionsplit",
            index=models.Index(
                fields=["transaction", "category"],
                name="transaction_transac_d94337_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="transactionsplit",
            index=models.Index(
                fields=["member", "created_at"], name="transaction_member__d6c4c8_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="transactiontag",
            unique_together={("household", "name")},
        ),
        migrations.AddIndex(
            model_name="transaction",
            index=models.Index(fields=["uuid"], name="transaction_uuid_0cf04c_idx"),
        ),
        migrations.AddIndex(
            model_name="transaction",
            index=models.Index(
                fields=["account", "date"], name="transaction_account_f34883_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="transaction",
            index=models.Index(
                fields=["category", "date"], name="transaction_categor_3ca96c_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="transaction",
            index=models.Index(
                fields=["transaction_type", "status", "date"],
                name="transaction_transac_b72ca1_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="transaction",
            index=models.Index(fields=["date"], name="transaction_date_7edf95_idx"),
        ),
        migrations.AddIndex(
            model_name="transaction",
            index=models.Index(
                fields=["account", "-date"], name="transaction_account_bed7b9_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="transaction",
            index=models.Index(
                fields=["status", "date"], name="transaction_status_719ef2_idx"
            ),
        ),
    ]
