# Generated by Django 5.2 on 2025-11-16 10:51

import uuid
from django.db import migrations, models


def generate_uuids(apps, schema_editor):
    """Generate unique UUIDs for all existing transactions."""
    transaction_model = apps.get_model("transactions", "Transaction")
    for transaction in transaction_model.objects.all():
        transaction.uuid = uuid.uuid4()
        transaction.save(update_fields=["uuid"])


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0005_add_uuid_field"),
        ("budgets", "0002_initial"),
        ("categories", "0003_alter_category_household"),
        ("goals", "0002_initial"),
        ("transactions", "0001_initial"),
    ]

    operations = [
        # Step 1: Add uuid field as nullable and non-unique
        migrations.AddField(
            model_name="transaction",
            name="uuid",
            field=models.UUIDField(
                db_index=True,
                editable=False,
                help_text="Unique identifier for API, webhooks, and idempotent imports",
                null=True,
                blank=True,
            ),
        ),
        # Step 2: Generate UUIDs for existing records
        migrations.RunPython(generate_uuids),
        # Step 3: Make uuid field non-nullable and unique
        migrations.AlterField(
            model_name="transaction",
            name="uuid",
            field=models.UUIDField(
                db_index=True,
                default=uuid.uuid4,
                editable=False,
                help_text="Unique identifier for API, webhooks, and idempotent imports",
                unique=True,
            ),
        ),
        # Step 4: Add index
        migrations.AddIndex(
            model_name="transaction",
            index=models.Index(fields=["uuid"], name="transaction_uuid_0cf04c_idx"),
        ),
    ]
