# Generated by Django 5.2 on 2025-11-17 04:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("transactions", "0002_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="transactionattachment",
            name="file",
            field=models.ImageField(
                help_text="Receipt or invoice image",
                upload_to="receipts/user_%s/%%Y/%%m/",
            ),
        ),
    ]
