# Generated by Django 5.2 on 2025-11-17 06:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("transactions", "0002_ocr_attachments"),
        ("transactions", "0003_alter_transactionattachment_file"),
    ]

    operations = []
