# Generated by Django 5.2 on 2025-11-17 01:20

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
        ("households", "0002_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("password", models.CharField(max_length=128, verbose_name="password")),
                (
                    "last_login",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="last login"
                    ),
                ),
                (
                    "is_superuser",
                    models.BooleanField(
                        default=False,
                        help_text="Designates that this user has all permissions without explicitly assigning them.",
                        verbose_name="superuser status",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now, editable=False
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "uuid",
                    models.UUIDField(
                        db_index=True,
                        default=uuid.uuid4,
                        editable=False,
                        help_text="Unique UUID for external API references",
                        unique=True,
                    ),
                ),
                (
                    "username",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        help_text="Username for login (alternative to email)",
                        max_length=150,
                        null=True,
                        unique=True,
                    ),
                ),
                (
                    "email",
                    models.EmailField(db_index=True, max_length=254, unique=True),
                ),
                ("email_verified", models.BooleanField(default=False)),
                ("first_name", models.CharField(blank=True, max_length=150)),
                ("last_name", models.CharField(blank=True, max_length=150)),
                (
                    "phone_number",
                    models.CharField(
                        blank=True,
                        max_length=17,
                        validators=[
                            django.core.validators.RegexValidator(
                                message="Phone number must be entered in the format: '+999999999'. Up to 15 digits allowed.",
                                regex="^\\+?1?\\d{9,15}$",
                            )
                        ],
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("is_staff", models.BooleanField(default=False)),
                (
                    "locale",
                    models.CharField(
                        choices=[
                            ("en", "English"),
                            ("en-nz", "English (New Zealand)"),
                            ("en-au", "English (Australia)"),
                            ("en-gb", "English (UK)"),
                            ("en-us", "English (US)"),
                        ],
                        default="en-nz",
                        max_length=10,
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("admin", "Admin"),
                            ("parent", "Parent"),
                            ("teen", "Teen"),
                            ("child", "Child"),
                            ("flatmate", "Flatmate"),
                            ("observer", "Observer"),
                        ],
                        default="observer",
                        max_length=20,
                    ),
                ),
                (
                    "groups",
                    models.ManyToManyField(
                        blank=True,
                        help_text="The groups this user belongs to. A user will get all permissions granted to each of their groups.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.group",
                        verbose_name="groups",
                    ),
                ),
                (
                    "household",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="users",
                        to="households.household",
                    ),
                ),
                (
                    "user_permissions",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Specific permissions for this user.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.permission",
                        verbose_name="user permissions",
                    ),
                ),
            ],
            options={
                "verbose_name": "User",
                "verbose_name_plural": "Users",
                "db_table": "users",
            },
        ),
        migrations.CreateModel(
            name="AccountUnlockToken",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now, editable=False
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "email",
                    models.EmailField(
                        db_index=True,
                        help_text="Email address of the locked account",
                        max_length=254,
                    ),
                ),
                (
                    "token",
                    models.UUIDField(
                        db_index=True,
                        default=uuid.uuid4,
                        editable=False,
                        help_text="Unique unlock token (UUID)",
                        unique=True,
                    ),
                ),
                (
                    "expires_at",
                    models.DateTimeField(
                        db_index=True, help_text="Token expiration timestamp"
                    ),
                ),
                (
                    "used_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="Timestamp when token was used (null if not used)",
                        null=True,
                    ),
                ),
                (
                    "ip_address",
                    models.GenericIPAddressField(
                        blank=True,
                        help_text="IP address that triggered the lockout",
                        null=True,
                    ),
                ),
            ],
            options={
                "verbose_name": "Account Unlock Token",
                "verbose_name_plural": "Account Unlock Tokens",
                "db_table": "account_unlock_tokens",
                "indexes": [
                    models.Index(
                        fields=["email", "expires_at"],
                        name="account_unl_email_d474ff_idx",
                    ),
                    models.Index(
                        fields=["token", "used_at"], name="account_unl_token_f3569d_idx"
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="EmailOTP",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now, editable=False
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "code",
                    models.CharField(
                        help_text="6-digit one-time password",
                        max_length=6,
                        validators=[
                            django.core.validators.RegexValidator(
                                message="OTP code must be exactly 6 digits",
                                regex="^\\d{6}$",
                            )
                        ],
                        verbose_name="OTP Code",
                    ),
                ),
                (
                    "expires_at",
                    models.DateTimeField(
                        help_text="When this OTP expires (10 minutes from creation)",
                        verbose_name="Expiration Time",
                    ),
                ),
                (
                    "is_used",
                    models.BooleanField(
                        db_index=True,
                        default=False,
                        help_text="Whether this OTP has been used",
                        verbose_name="Used",
                    ),
                ),
                (
                    "ip_address",
                    models.GenericIPAddressField(
                        blank=True,
                        help_text="IP address that requested this OTP",
                        null=True,
                        verbose_name="IP Address",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        help_text="User associated with this OTP",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="email_otps",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="User",
                    ),
                ),
            ],
            options={
                "verbose_name": "Email OTP",
                "verbose_name_plural": "Email OTPs",
                "db_table": "email_otp",
                "ordering": ["-created_at"],
                "permissions": [
                    ("can_generate_otp", "Can generate OTP codes"),
                    ("can_verify_otp", "Can verify OTP codes"),
                ],
            },
        ),
        migrations.CreateModel(
            name="EmailVerification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now, editable=False
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "token",
                    models.UUIDField(
                        db_index=True,
                        default=uuid.uuid4,
                        editable=False,
                        help_text="Unique token sent to user email",
                        unique=True,
                        verbose_name="Verification Token",
                    ),
                ),
                (
                    "verified_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="When email was verified",
                        null=True,
                        verbose_name="Verified At",
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        help_text="User to be verified",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="email_verification",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="User",
                    ),
                ),
            ],
            options={
                "verbose_name": "Email Verification",
                "verbose_name_plural": "Email Verifications",
                "db_table": "email_verification",
                "ordering": ["-created_at"],
                "permissions": [
                    ("can_verify_email", "Can verify user emails"),
                    ("can_resend_verification", "Can resend verification emails"),
                ],
            },
        ),
        migrations.CreateModel(
            name="UserMFADevice",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now, editable=False
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("secret_key", models.CharField(max_length=64)),
                ("is_enabled", models.BooleanField(default=False)),
                ("backup_codes", models.JSONField(blank=True, default=list)),
                ("last_used_at", models.DateTimeField(blank=True, null=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="mfa_device",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "MFA device",
                "verbose_name_plural": "MFA devices",
            },
        ),
        migrations.AddIndex(
            model_name="user",
            index=models.Index(
                fields=["email", "is_active"], name="users_email_a7cfd1_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="user",
            index=models.Index(
                fields=["username", "is_active"], name="users_usernam_b4c624_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="user",
            index=models.Index(fields=["uuid"], name="users_uuid_4cb658_idx"),
        ),
        migrations.AddIndex(
            model_name="emailotp",
            index=models.Index(
                fields=["user", "-created_at"], name="email_otp_user_id_8aa2fa_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="emailotp",
            index=models.Index(
                fields=["code", "is_used"], name="email_otp_code_0eb30c_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="emailotp",
            index=models.Index(
                fields=["expires_at", "is_used"], name="email_otp_expires_dfe2f0_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="emailverification",
            index=models.Index(fields=["token"], name="email_verif_token_5274ac_idx"),
        ),
        migrations.AddIndex(
            model_name="emailverification",
            index=models.Index(
                fields=["user", "verified_at"], name="email_verif_user_id_a36a6e_idx"
            ),
        ),
    ]
