# Generated by Django 5.2 on 2025-11-16 20:51

import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="AccountUnlockToken",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now, editable=False
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "email",
                    models.EmailField(
                        db_index=True,
                        help_text="Email address of the locked account",
                        max_length=254,
                    ),
                ),
                (
                    "token",
                    models.UUIDField(
                        db_index=True,
                        default=uuid.uuid4,
                        editable=False,
                        help_text="Unique unlock token (UUID)",
                        unique=True,
                    ),
                ),
                (
                    "expires_at",
                    models.DateTimeField(
                        db_index=True, help_text="Token expiration timestamp"
                    ),
                ),
                (
                    "used_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="Timestamp when token was used (null if not used)",
                        null=True,
                    ),
                ),
                (
                    "ip_address",
                    models.GenericIPAddressField(
                        blank=True,
                        help_text="IP address that triggered the lockout",
                        null=True,
                    ),
                ),
            ],
            options={
                "verbose_name": "Account Unlock Token",
                "verbose_name_plural": "Account Unlock Tokens",
                "db_table": "account_unlock_tokens",
                "indexes": [
                    models.Index(
                        fields=["email", "expires_at"],
                        name="account_unl_email_d474ff_idx",
                    ),
                    models.Index(
                        fields=["token", "used_at"], name="account_unl_token_f3569d_idx"
                    ),
                ],
            },
        ),
    ]
