# Generated by Django 5.2 on 2025-11-15 01:16

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_usermfadevice"),
    ]

    operations = [
        migrations.CreateModel(
            name="EmailOTP",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now, editable=False
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "code",
                    models.CharField(
                        help_text="6-digit one-time password",
                        max_length=6,
                        validators=[
                            django.core.validators.RegexValidator(
                                message="OTP code must be exactly 6 digits",
                                regex="^\\d{6}$",
                            )
                        ],
                        verbose_name="OTP Code",
                    ),
                ),
                (
                    "expires_at",
                    models.DateTimeField(
                        help_text="When this OTP expires (10 minutes from creation)",
                        verbose_name="Expiration Time",
                    ),
                ),
                (
                    "is_used",
                    models.BooleanField(
                        db_index=True,
                        default=False,
                        help_text="Whether this OTP has been used",
                        verbose_name="Used",
                    ),
                ),
                (
                    "ip_address",
                    models.GenericIPAddressField(
                        blank=True,
                        help_text="IP address that requested this OTP",
                        null=True,
                        verbose_name="IP Address",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        help_text="User associated with this OTP",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="email_otps",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="User",
                    ),
                ),
            ],
            options={
                "verbose_name": "Email OTP",
                "verbose_name_plural": "Email OTPs",
                "db_table": "email_otp",
                "ordering": ["-created_at"],
                "permissions": [
                    ("can_generate_otp", "Can generate OTP codes"),
                    ("can_verify_otp", "Can verify OTP codes"),
                ],
                "indexes": [
                    models.Index(
                        fields=["user", "-created_at"],
                        name="email_otp_user_id_8aa2fa_idx",
                    ),
                    models.Index(
                        fields=["code", "is_used"], name="email_otp_code_0eb30c_idx"
                    ),
                    models.Index(
                        fields=["expires_at", "is_used"],
                        name="email_otp_expires_dfe2f0_idx",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="EmailVerification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now, editable=False
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "token",
                    models.UUIDField(
                        db_index=True,
                        default=uuid.uuid4,
                        editable=False,
                        help_text="Unique token sent to user email",
                        unique=True,
                        verbose_name="Verification Token",
                    ),
                ),
                (
                    "verified_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="When email was verified",
                        null=True,
                        verbose_name="Verified At",
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        help_text="User to be verified",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="email_verification",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="User",
                    ),
                ),
            ],
            options={
                "verbose_name": "Email Verification",
                "verbose_name_plural": "Email Verifications",
                "db_table": "email_verification",
                "ordering": ["-created_at"],
                "permissions": [
                    ("can_verify_email", "Can verify user emails"),
                    ("can_resend_verification", "Can resend verification emails"),
                ],
                "indexes": [
                    models.Index(fields=["token"], name="email_verif_token_5274ac_idx"),
                    models.Index(
                        fields=["user", "verified_at"],
                        name="email_verif_user_id_a36a6e_idx",
                    ),
                ],
            },
        ),
    ]
