# Generated by Django 5.2 on 2025-11-16 10:39

import uuid
from django.db import migrations, models


def generate_uuids(apps, schema_editor):
    """Generate unique UUIDs for existing users."""
    user_model = apps.get_model("users", "User")
    for user in user_model.objects.all():
        if not user.uuid or user.uuid == uuid.UUID(
            "04f3f0f8-6a3c-4d49-88c0-366dd6bce43b"
        ):
            user.uuid = uuid.uuid4()
            user.save(update_fields=["uuid"])


class Migration(migrations.Migration):

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
        (
            "households",
            "0004_remove_membership_memberships_user_id_b0e170_idx_and_more",
        ),
        ("users", "0003_emailotp_emailverification"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="uuid",
            field=models.UUIDField(
                db_index=True,
                default=uuid.uuid4,
                editable=False,
                help_text="Unique UUID for external API references",
                unique=False,  # Temporarily not unique
            ),
        ),
        migrations.RunPython(generate_uuids),
        migrations.AlterField(
            model_name="user",
            name="uuid",
            field=models.UUIDField(
                db_index=True,
                default=uuid.uuid4,
                editable=False,
                help_text="Unique UUID for external API references",
                unique=True,  # Make unique after UUIDs are generated
            ),
        ),
        migrations.AddIndex(
            model_name="user",
            index=models.Index(fields=["uuid"], name="users_uuid_4cb658_idx"),
        ),
    ]
