# Generated by Django 5.2 on 2025-11-16 10:40

import uuid
from django.db import migrations, models


def gen_uuid(apps, schema_editor):
    """Generate unique UUIDs for all existing users."""
    user_model = apps.get_model("users", "User")
    for user_obj in user_model.objects.all():
        user_obj.uuid = uuid.uuid4()
        user_obj.save(update_fields=["uuid"])


class Migration(migrations.Migration):

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
        (
            "households",
            "0004_remove_membership_memberships_user_id_b0e170_idx_and_more",
        ),
        ("users", "0003_emailotp_emailverification"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="uuid",
            field=models.UUIDField(
                db_index=True,
                default=uuid.uuid4,
                editable=False,
                help_text="Unique UUID for external API references",
                unique=False,
            ),
        ),
        migrations.RunPython(gen_uuid),
        migrations.AlterField(
            model_name="user",
            name="uuid",
            field=models.UUIDField(
                db_index=True,
                default=uuid.uuid4,
                editable=False,
                help_text="Unique UUID for external API references",
                unique=True,
            ),
        ),
        migrations.AddIndex(
            model_name="user",
            index=models.Index(fields=["uuid"], name="users_uuid_4cb658_idx"),
        ),
    ]
