# Generated by Django 5.2 on 2025-11-16 10:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0004_add_uuid_field"),
        ("users", "0004_user_uuid_user_users_uuid_4cb658_idx"),
    ]

    operations = []
