# Generated by Django 5.2 on 2025-11-16 11:07

import uuid
from django.db import migrations, models


def generate_usernames(apps, schema_editor):
    """Generate usernames from emails for existing users."""
    user_model = apps.get_model("users", "User")
    existing_usernames = set()

    for user in user_model.objects.all():
        # Generate username from email (part before @)
        base_username = user.email.split("@")[0].lower()
        username = base_username
        counter = 1

        # Ensure uniqueness by appending counter if needed
        while (
            username in existing_usernames
            or user_model.objects.filter(username=username).exists()
        ):
            username = f"{base_username}{counter}"
            counter += 1

        user.username = username
        existing_usernames.add(username)
        user.save(update_fields=["username"])


def reverse_usernames(apps, schema_editor):
    """Reverse: clear all usernames."""
    user_model = apps.get_model("users", "User")
    user_model.objects.all().update(username=None)


class Migration(migrations.Migration):

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
        ("households", "0005_add_uuid_field"),
        ("users", "0005_merge_20251116_2356"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="username",
            field=models.CharField(
                blank=True,
                db_index=True,
                help_text="Username for login (alternative to email)",
                max_length=150,
                null=True,
                unique=True,
            ),
        ),
        migrations.RunPython(generate_usernames, reverse_usernames),
        migrations.AddIndex(
            model_name="user",
            index=models.Index(
                fields=["username", "is_active"], name="users_usernam_b4c624_idx"
            ),
        ),
    ]
