# Generated by Django 5.2 on 2025-11-16 20:04

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("budgets", "0002_initial"),
        ("goals", "0002_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Reward",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now, editable=False
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "reward_type",
                    models.CharField(
                        choices=[
                            ("milestone", "Milestone Achievement"),
                            ("streak", "Streak Completion"),
                            ("budget_saved", "Budget Savings"),
                            ("goal_reached", "Goal Reached"),
                            ("consistent_logging", "Consistent Logging"),
                            ("debt_paid", "Debt Paid Off"),
                            ("first_transaction", "First Transaction"),
                            ("first_budget", "First Budget Created"),
                            ("first_goal", "First Goal Created"),
                            ("custom", "Custom Reward"),
                        ],
                        help_text="Type of reward earned",
                        max_length=30,
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        help_text="Reward title (e.g., 'Budget Master', 'Savings Star')",
                        max_length=255,
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True, help_text="Description of what this reward is for"
                    ),
                ),
                (
                    "icon",
                    models.CharField(
                        blank=True,
                        help_text="Icon or emoji for reward display (e.g., '🏆', '⭐', '🎉')",
                        max_length=50,
                    ),
                ),
                (
                    "badge_image",
                    models.ImageField(
                        blank=True,
                        help_text="Optional badge image",
                        null=True,
                        upload_to="rewards/badges/",
                    ),
                ),
                (
                    "earned_on",
                    models.DateTimeField(help_text="When this reward was earned"),
                ),
                (
                    "points",
                    models.PositiveIntegerField(
                        default=0, help_text="Points value of this reward"
                    ),
                ),
                (
                    "is_visible",
                    models.BooleanField(
                        default=True, help_text="Whether this reward is visible to user"
                    ),
                ),
                (
                    "related_budget",
                    models.ForeignKey(
                        blank=True,
                        help_text="Budget that triggered this reward (if applicable)",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="rewards",
                        to="budgets.budget",
                    ),
                ),
                (
                    "related_goal",
                    models.ForeignKey(
                        blank=True,
                        help_text="Goal that triggered this reward (if applicable)",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="rewards",
                        to="goals.goal",
                    ),
                ),
            ],
            options={
                "verbose_name": "Reward",
                "verbose_name_plural": "Rewards",
                "db_table": "rewards",
                "ordering": ["-earned_on"],
            },
        ),
    ]
