# Generated by Django 5.2 on 2025-11-17 01:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("rewards", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="reward",
            name="user",
            field=models.ForeignKey(
                help_text="User who earned this reward",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="rewards",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddIndex(
            model_name="reward",
            index=models.Index(
                fields=["user", "earned_on"], name="rewards_user_id_1a4b6f_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="reward",
            index=models.Index(
                fields=["user", "reward_type"], name="rewards_user_id_47228f_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="reward",
            index=models.Index(fields=["earned_on"], name="rewards_earned__72f093_idx"),
        ),
    ]
