# Generated by Django 5.2 on 2025-11-17 01:20

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Budget",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now, editable=False
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "name",
                    models.CharField(
                        help_text="Budget name (e.g., 'January 2024 Budget', 'Q1 2024')",
                        max_length=255,
                    ),
                ),
                ("start_date", models.DateField(help_text="Budget period start date")),
                ("end_date", models.DateField(help_text="Budget period end date")),
                (
                    "cycle_type",
                    models.CharField(
                        choices=[
                            ("weekly", "Weekly"),
                            ("fortnightly", "Fortnightly"),
                            ("monthly", "Monthly"),
                            ("quarterly", "Quarterly"),
                            ("yearly", "Yearly"),
                            ("custom", "Custom"),
                        ],
                        default="monthly",
                        help_text="Budget cycle/period type",
                        max_length=20,
                    ),
                ),
                (
                    "total_amount",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Total budget amount for this period",
                        max_digits=12,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("completed", "Completed"),
                            ("exceeded", "Exceeded"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="active",
                        help_text="Current budget status",
                        max_length=20,
                    ),
                ),
                (
                    "alert_threshold",
                    models.DecimalField(
                        decimal_places=2,
                        default=80.0,
                        help_text="Alert when spending reaches this percentage (e.g., 80.00)",
                        max_digits=5,
                    ),
                ),
                (
                    "rollover_enabled",
                    models.BooleanField(
                        default=False,
                        help_text="Whether unused budget rolls over to next period",
                    ),
                ),
                (
                    "notes",
                    models.TextField(blank=True, help_text="Optional budget notes"),
                ),
            ],
            options={
                "verbose_name": "Budget",
                "verbose_name_plural": "Budgets",
                "db_table": "budgets",
                "ordering": ["-start_date", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="BudgetItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now, editable=False
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "name",
                    models.CharField(help_text="Budget item name", max_length=255),
                ),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Allocated amount for this budget item",
                        max_digits=12,
                    ),
                ),
                (
                    "notes",
                    models.TextField(
                        blank=True, help_text="Optional notes for this budget item"
                    ),
                ),
            ],
            options={
                "verbose_name": "Budget Item",
                "verbose_name_plural": "Budget Items",
                "db_table": "budget_items",
                "ordering": ["name"],
            },
        ),
    ]
