# Generated by Django 5.2 on 2025-11-13 00:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("budgets", "0001_initial"),
        ("categories", "0001_initial"),
        ("households", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="budget",
            name="household",
            field=models.ForeignKey(
                help_text="Household this budget belongs to",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="budgets",
                to="households.household",
            ),
        ),
        migrations.AddField(
            model_name="budgetitem",
            name="budget",
            field=models.ForeignKey(
                help_text="Parent budget this item belongs to",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="items",
                to="budgets.budget",
            ),
        ),
        migrations.AddField(
            model_name="budgetitem",
            name="category",
            field=models.ForeignKey(
                blank=True,
                help_text="Category this budget item tracks (optional)",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="budget_items",
                to="categories.category",
            ),
        ),
        migrations.AddIndex(
            model_name="budget",
            index=models.Index(
                fields=["household", "start_date", "end_date"],
                name="budgets_househo_859b51_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="budget",
            index=models.Index(
                fields=["household", "status"], name="budgets_househo_9c14db_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="budget",
            index=models.Index(
                fields=["start_date", "end_date"], name="budgets_start_d_6720b3_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="budgetitem",
            index=models.Index(
                fields=["budget", "category"], name="budget_item_budget__fab1c1_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="budgetitem",
            unique_together={("budget", "name")},
        ),
    ]
