# Generated by Django 5.2 on 2025-11-16 20:04

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Household",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now, editable=False
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "uuid",
                    models.UUIDField(
                        db_index=True,
                        default=uuid.uuid4,
                        editable=False,
                        help_text="Unique identifier for API and external integrations",
                        unique=True,
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                (
                    "household_type",
                    models.CharField(
                        choices=[
                            ("fam", "Family"),
                            ("couple", "Couple"),
                            ("student", "Student Flat"),
                            ("single", "Individual"),
                            ("cpl", "Couple"),
                            ("stud", "Student Flat"),
                            ("ind", "Individual"),
                        ],
                        default="fam",
                        max_length=10,
                    ),
                ),
                (
                    "budget_cycle",
                    models.CharField(
                        choices=[
                            ("d", "Daily"),
                            ("w", "Weekly"),
                            ("f", "Fortnightly"),
                            ("m", "Monthly"),
                            ("c", "Custom"),
                        ],
                        default="m",
                        max_length=1,
                    ),
                ),
            ],
            options={
                "verbose_name": "Household",
                "verbose_name_plural": "Households",
                "db_table": "households",
                "indexes": [
                    models.Index(fields=["uuid"], name="households_uuid_b91a45_idx")
                ],
            },
        ),
        migrations.CreateModel(
            name="Membership",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now, editable=False
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "membership_type",
                    models.CharField(
                        choices=[
                            ("sw", "Starter Whānau"),
                            ("fw", "Future Whānau"),
                            ("mm", "Money Mates"),
                            ("wp", "Whānau Plus"),
                            ("ww", "Whānau Works"),
                            ("if", "Individual Freemium"),
                        ],
                        default="sw",
                        max_length=2,
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("admin", "Admin"),
                            ("parent", "Parent"),
                            ("teen", "Teen"),
                            ("child", "Child"),
                            ("flatmate", "Flatmate"),
                            ("observer", "Observer"),
                        ],
                        default="observer",
                        max_length=20,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("inactive", "Inactive"),
                            ("pending", "Pending"),
                            ("cancelled", "Cancelled"),
                            ("expired", "Expired"),
                        ],
                        default="active",
                        max_length=20,
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Boolean mirror of status='active'. Tests filter heavily on this.",
                    ),
                ),
                (
                    "start_date",
                    models.DateTimeField(
                        auto_now_add=True, help_text="When user joined this household"
                    ),
                ),
                (
                    "ended_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="Auto-set when membership is cancelled/expired",
                        null=True,
                    ),
                ),
                (
                    "is_primary",
                    models.BooleanField(
                        default=False,
                        help_text="User may only have one primary household",
                    ),
                ),
                (
                    "billing_cycle",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("d", "Daily"),
                            ("w", "Weekly"),
                            ("f", "Fortnightly"),
                            ("m", "Monthly"),
                            ("c", "Custom"),
                        ],
                        max_length=1,
                        null=True,
                    ),
                ),
                ("next_billing_date", models.DateField(blank=True, null=True)),
                (
                    "amount",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "payment_status",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("paid", "Paid"),
                            ("pending", "Pending"),
                            ("overdue", "Overdue"),
                            ("failed", "Failed"),
                        ],
                        max_length=20,
                        null=True,
                    ),
                ),
                (
                    "household",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="memberships",
                        to="households.household",
                    ),
                ),
            ],
            options={
                "verbose_name": "Membership",
                "verbose_name_plural": "Memberships",
                "db_table": "memberships",
                "ordering": ["-is_primary", "-created_at"],
            },
        ),
    ]
