# Generated by Django 5.2 on 2025-11-13 00:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("households", "0001_initial"),
        ("organisations", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="membership",
            name="organisation",
            field=models.ForeignKey(
                blank=True,
                help_text="Optional organisation link for 'Whānau Works' memberships",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="memberships",
                to="organisations.organisation",
            ),
        ),
    ]
