# Generated by Django 5.2 on 2025-11-13 00:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("households", "0002_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="membership",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="memberships",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddIndex(
            model_name="membership",
            index=models.Index(
                fields=["user", "status"], name="memberships_user_id_b0e170_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="membership",
            index=models.Index(
                fields=["household", "status"], name="memberships_househo_6dd8f7_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="membership",
            index=models.Index(
                fields=["user", "is_primary"], name="memberships_user_id_0ef822_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="membership",
            index=models.Index(
                fields=["status", "end_date"], name="memberships_status_fe4c2b_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="membership",
            unique_together={("user", "household")},
        ),
    ]
