# Generated by Django 5.2 on 2025-11-14 00:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("households", "0003_initial"),
        ("organisations", "0002_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="membership",
            name="memberships_user_id_b0e170_idx",
        ),
        migrations.RemoveIndex(
            model_name="membership",
            name="memberships_househo_6dd8f7_idx",
        ),
        migrations.RemoveIndex(
            model_name="membership",
            name="memberships_status_fe4c2b_idx",
        ),
        migrations.RenameField(
            model_name="membership",
            old_name="end_date",
            new_name="ended_at",
        ),
        migrations.AddField(
            model_name="membership",
            name="is_active",
            field=models.BooleanField(
                default=True,
                help_text="Boolean mirror of status='active'. Tests filter heavily on this.",
            ),
        ),
        migrations.AlterField(
            model_name="membership",
            name="amount",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=10, null=True
            ),
        ),
        migrations.AlterField(
            model_name="membership",
            name="billing_cycle",
            field=models.CharField(
                blank=True,
                choices=[
                    ("d", "Daily"),
                    ("w", "Weekly"),
                    ("f", "Fortnightly"),
                    ("m", "Monthly"),
                    ("c", "Custom"),
                ],
                max_length=1,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="membership",
            name="is_primary",
            field=models.BooleanField(
                default=False, help_text="User may only have one primary household"
            ),
        ),
        migrations.AlterField(
            model_name="membership",
            name="membership_type",
            field=models.CharField(
                choices=[
                    ("sw", "Starter Whānau"),
                    ("fw", "Future Whānau"),
                    ("mm", "Money Mates"),
                    ("wp", "Whānau Plus"),
                    ("ww", "Whānau Works"),
                    ("if", "Individual Freemium"),
                ],
                default="sw",
                max_length=2,
            ),
        ),
        migrations.AlterField(
            model_name="membership",
            name="next_billing_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="membership",
            name="organisation",
            field=models.ForeignKey(
                blank=True,
                help_text="Optional / Whānau Works memberships",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="memberships",
                to="organisations.organisation",
            ),
        ),
        migrations.AlterField(
            model_name="membership",
            name="payment_status",
            field=models.CharField(
                blank=True,
                choices=[
                    ("paid", "Paid"),
                    ("pending", "Pending"),
                    ("overdue", "Overdue"),
                    ("failed", "Failed"),
                ],
                max_length=20,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="membership",
            name="role",
            field=models.CharField(
                choices=[
                    ("admin", "Admin"),
                    ("parent", "Parent"),
                    ("teen", "Teen"),
                    ("child", "Child"),
                    ("flatmate", "Flatmate"),
                    ("observer", "Observer"),
                ],
                default="observer",
                max_length=20,
            ),
        ),
        migrations.AddIndex(
            model_name="membership",
            index=models.Index(
                fields=["user", "is_active"], name="memberships_user_id_1684f6_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="membership",
            index=models.Index(
                fields=["household", "is_active"], name="memberships_househo_c7d116_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="membership",
            index=models.Index(
                fields=["is_active", "ended_at"], name="memberships_is_acti_1a039c_idx"
            ),
        ),
    ]
