# Generated by Django 5.2 on 2025-11-16 10:47

import uuid
from django.db import migrations, models


def generate_uuids(apps, schema_editor):
    """Generate unique UUIDs for all existing households."""
    household_model = apps.get_model("households", "Household")
    for household in household_model.objects.all():
        household.uuid = uuid.uuid4()
        household.save(update_fields=["uuid"])


class Migration(migrations.Migration):

    dependencies = [
        (
            "households",
            "0004_remove_membership_memberships_user_id_b0e170_idx_and_more",
        ),
    ]

    operations = [
        # Step 1: Add uuid field as nullable and non-unique
        migrations.AddField(
            model_name="household",
            name="uuid",
            field=models.UUIDField(
                db_index=True,
                editable=False,
                help_text="Unique identifier for API and external integrations",
                null=True,
                blank=True,
            ),
        ),
        # Step 2: Generate UUIDs for existing records
        migrations.RunPython(generate_uuids),
        # Step 3: Make uuid field non-nullable and unique
        migrations.AlterField(
            model_name="household",
            name="uuid",
            field=models.UUIDField(
                db_index=True,
                default=uuid.uuid4,
                editable=False,
                help_text="Unique identifier for API and external integrations",
                unique=True,
            ),
        ),
        # Step 4: Add index
        migrations.AddIndex(
            model_name="household",
            index=models.Index(fields=["uuid"], name="households_uuid_b91a45_idx"),
        ),
    ]
