# Generated by Django 5.2 on 2025-11-13 16:35

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("households", "0003_initial"),
        ("organisations", "0002_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AuditLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now, editable=False
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "action_type",
                    models.CharField(
                        choices=[
                            ("LOGIN", "User Login"),
                            ("LOGOUT", "User Logout"),
                            ("LOGIN_FAILED", "Failed Login Attempt"),
                            ("PASSWORD_CHANGE", "Password Changed"),
                            ("MFA_ENABLED", "MFA Enabled"),
                            ("MFA_DISABLED", "MFA Disabled"),
                            ("CREATE", "Create"),
                            ("UPDATE", "Update"),
                            ("DELETE", "Delete"),
                            ("VIEW", "View"),
                            ("EXPORT", "Data Export"),
                            ("IMPORT", "Data Import"),
                            ("BULK_DELETE", "Bulk Delete"),
                            ("PERMISSION_GRANT", "Permission Granted"),
                            ("PERMISSION_REVOKE", "Permission Revoked"),
                            ("ROLE_CHANGE", "Role Changed"),
                            ("RATE_LIMIT_EXCEEDED", "Rate Limit Exceeded"),
                            ("ACCOUNT_LOCKED", "Account Locked"),
                            ("ACCOUNT_UNLOCKED", "Account Unlocked"),
                        ],
                        db_index=True,
                        help_text="Type of action performed",
                        max_length=50,
                    ),
                ),
                (
                    "action_description",
                    models.TextField(
                        help_text="Human-readable description of the action"
                    ),
                ),
                (
                    "object_type",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        help_text="Model name of affected object (e.g., 'Transaction', 'Budget')",
                        max_length=100,
                    ),
                ),
                (
                    "object_id",
                    models.PositiveIntegerField(
                        blank=True,
                        db_index=True,
                        help_text="Primary key of affected object",
                        null=True,
                    ),
                ),
                (
                    "object_repr",
                    models.CharField(
                        blank=True,
                        help_text="String representation of affected object",
                        max_length=255,
                    ),
                ),
                (
                    "ip_address",
                    models.GenericIPAddressField(
                        blank=True, help_text="IP address of the request", null=True
                    ),
                ),
                (
                    "user_agent",
                    models.TextField(
                        blank=True, help_text="User agent string from request"
                    ),
                ),
                (
                    "request_path",
                    models.CharField(
                        blank=True, help_text="URL path of the request", max_length=500
                    ),
                ),
                (
                    "request_method",
                    models.CharField(
                        blank=True,
                        help_text="HTTP method (GET, POST, etc.)",
                        max_length=10,
                    ),
                ),
                (
                    "changes",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Dictionary of changed fields: {field: {'old': value, 'new': value}}",
                    ),
                ),
                (
                    "metadata",
                    models.JSONField(
                        blank=True, default=dict, help_text="Additional contextual data"
                    ),
                ),
                (
                    "success",
                    models.BooleanField(
                        default=True, help_text="Whether the action was successful"
                    ),
                ),
                (
                    "error_message",
                    models.TextField(
                        blank=True, help_text="Error message if action failed"
                    ),
                ),
                (
                    "household",
                    models.ForeignKey(
                        blank=True,
                        help_text="Household context (if applicable)",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="audit_logs",
                        to="households.household",
                    ),
                ),
                (
                    "organisation",
                    models.ForeignKey(
                        blank=True,
                        help_text="Organisation context (if applicable)",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="audit_logs",
                        to="organisations.organisation",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        help_text="User who performed the action (null for system actions)",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="audit_logs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Audit Log",
                "verbose_name_plural": "Audit Logs",
                "db_table": "audit_logs",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["-created_at", "user"],
                        name="audit_logs_created_101e9b_idx",
                    ),
                    models.Index(
                        fields=["action_type", "-created_at"],
                        name="audit_logs_action__a429dc_idx",
                    ),
                    models.Index(
                        fields=["household", "-created_at"],
                        name="audit_logs_househo_9d1c7b_idx",
                    ),
                    models.Index(
                        fields=["object_type", "object_id"],
                        name="audit_logs_object__457405_idx",
                    ),
                    models.Index(
                        fields=["ip_address", "-created_at"],
                        name="audit_logs_ip_addr_190b84_idx",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="DataExportLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now, editable=False
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "export_type",
                    models.CharField(
                        choices=[
                            ("household_backup", "Household Full Backup"),
                            ("transaction_export", "Transaction Export"),
                            ("budget_report", "Budget Report"),
                            ("spending_report", "Spending Report"),
                            ("user_data_export", "User Personal Data Export (GDPR)"),
                        ],
                        db_index=True,
                        help_text="Type of data export",
                        max_length=50,
                    ),
                ),
                (
                    "record_count",
                    models.PositiveIntegerField(help_text="Number of records exported"),
                ),
                (
                    "date_range_start",
                    models.DateField(
                        blank=True,
                        help_text="Start date of exported data range",
                        null=True,
                    ),
                ),
                (
                    "date_range_end",
                    models.DateField(
                        blank=True,
                        help_text="End date of exported data range",
                        null=True,
                    ),
                ),
                (
                    "ip_address",
                    models.GenericIPAddressField(
                        help_text="IP address of export request"
                    ),
                ),
                (
                    "user_agent",
                    models.TextField(blank=True, help_text="User agent string"),
                ),
                (
                    "file_format",
                    models.CharField(
                        default="json",
                        help_text="Export file format (json, csv, xlsx, pdf)",
                        max_length=20,
                    ),
                ),
                (
                    "file_size_bytes",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="Size of exported file in bytes",
                        null=True,
                    ),
                ),
                (
                    "export_filters",
                    models.JSONField(
                        blank=True, default=dict, help_text="Filters applied to export"
                    ),
                ),
                (
                    "household",
                    models.ForeignKey(
                        blank=True,
                        help_text="Household context",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="data_exports",
                        to="households.household",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        help_text="User who requested the export",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="data_exports",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Data Export Log",
                "verbose_name_plural": "Data Export Logs",
                "db_table": "data_export_logs",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["-created_at", "user"],
                        name="data_export_created_04fa84_idx",
                    ),
                    models.Index(
                        fields=["export_type", "-created_at"],
                        name="data_export_export__bf718a_idx",
                    ),
                    models.Index(
                        fields=["household", "-created_at"],
                        name="data_export_househo_04a368_idx",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="FailedLoginAttempt",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now, editable=False
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "username",
                    models.CharField(
                        db_index=True,
                        help_text="Attempted username/email",
                        max_length=255,
                    ),
                ),
                (
                    "ip_address",
                    models.GenericIPAddressField(
                        db_index=True, help_text="IP address of attempt"
                    ),
                ),
                (
                    "user_agent",
                    models.TextField(blank=True, help_text="User agent string"),
                ),
                (
                    "request_path",
                    models.CharField(
                        blank=True, help_text="Login endpoint path", max_length=500
                    ),
                ),
                (
                    "attempt_count",
                    models.PositiveIntegerField(
                        default=1,
                        help_text="Number of consecutive failures from this IP",
                    ),
                ),
                (
                    "locked_out",
                    models.BooleanField(
                        default=False,
                        help_text="Whether this attempt resulted in account lockout",
                    ),
                ),
                (
                    "resolved",
                    models.BooleanField(
                        default=False,
                        help_text="Whether this security event has been reviewed",
                    ),
                ),
                (
                    "notes",
                    models.TextField(
                        blank=True, help_text="Admin notes about this security event"
                    ),
                ),
                (
                    "resolved_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="Admin who reviewed this attempt",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="resolved_login_attempts",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Failed Login Attempt",
                "verbose_name_plural": "Failed Login Attempts",
                "db_table": "failed_login_attempts",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["-created_at", "ip_address"],
                        name="failed_logi_created_667595_idx",
                    ),
                    models.Index(
                        fields=["username", "-created_at"],
                        name="failed_logi_usernam_3f2a83_idx",
                    ),
                    models.Index(
                        fields=["resolved", "-created_at"],
                        name="failed_logi_resolve_3ff0f8_idx",
                    ),
                ],
            },
        ),
    ]
