# Generated by Django 5.2 on 2025-11-16 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("audit", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="auditlog",
            name="action_type",
            field=models.CharField(
                choices=[
                    ("LOGIN", "User Login"),
                    ("LOGOUT", "User Logout"),
                    ("LOGIN_FAILED", "Failed Login Attempt"),
                    ("PASSWORD_CHANGE", "Password Changed"),
                    ("MFA_ENABLED", "MFA Enabled"),
                    ("MFA_DISABLED", "MFA Disabled"),
                    ("CREATE", "Create"),
                    ("UPDATE", "Update"),
                    ("DELETE", "Delete"),
                    ("VIEW", "View"),
                    ("EXPORT", "Data Export"),
                    ("IMPORT", "Data Import"),
                    ("BULK_DELETE", "Bulk Delete"),
                    ("PERMISSION_GRANT", "Permission Granted"),
                    ("PERMISSION_REVOKE", "Permission Revoked"),
                    ("ROLE_CHANGE", "Role Changed"),
                    ("RATE_LIMIT_EXCEEDED", "Rate Limit Exceeded"),
                    ("ACCOUNT_LOCKED", "Account Locked"),
                    ("ACCOUNT_UNLOCKED", "Account Unlocked"),
                    ("EMAIL_VERIFIED", "Email Verified"),
                    ("OTP_REQUESTED", "OTP Requested"),
                ],
                db_index=True,
                help_text="Type of action performed",
                max_length=50,
            ),
        ),
    ]
