# Generated by Django 5.2 on 2025-11-17 01:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("audit", "0002_initial"),
        ("organisations", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="auditlog",
            name="organisation",
            field=models.ForeignKey(
                blank=True,
                help_text="Organisation context (if applicable)",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="audit_logs",
                to="organisations.organisation",
            ),
        ),
    ]
