# Generated by Django 5.2 on 2025-11-17 01:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("audit", "0003_initial"),
        ("households", "0002_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="auditlog",
            name="user",
            field=models.ForeignKey(
                blank=True,
                help_text="User who performed the action (null for system actions)",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="audit_logs",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="dataexportlog",
            name="household",
            field=models.ForeignKey(
                blank=True,
                help_text="Household context",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="data_exports",
                to="households.household",
            ),
        ),
        migrations.AddField(
            model_name="dataexportlog",
            name="user",
            field=models.ForeignKey(
                help_text="User who requested the export",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="data_exports",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="failedloginattempt",
            name="resolved_by",
            field=models.ForeignKey(
                blank=True,
                help_text="Admin who reviewed this attempt",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="resolved_login_attempts",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddIndex(
            model_name="auditlog",
            index=models.Index(
                fields=["-created_at", "user"], name="audit_logs_created_101e9b_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="auditlog",
            index=models.Index(
                fields=["action_type", "-created_at"],
                name="audit_logs_action__a429dc_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="auditlog",
            index=models.Index(
                fields=["household", "-created_at"],
                name="audit_logs_househo_9d1c7b_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="auditlog",
            index=models.Index(
                fields=["object_type", "object_id"],
                name="audit_logs_object__457405_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="auditlog",
            index=models.Index(
                fields=["ip_address", "-created_at"],
                name="audit_logs_ip_addr_190b84_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="dataexportlog",
            index=models.Index(
                fields=["-created_at", "user"], name="data_export_created_04fa84_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="dataexportlog",
            index=models.Index(
                fields=["export_type", "-created_at"],
                name="data_export_export__bf718a_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="dataexportlog",
            index=models.Index(
                fields=["household", "-created_at"],
                name="data_export_househo_04a368_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="failedloginattempt",
            index=models.Index(
                fields=["-created_at", "ip_address"],
                name="failed_logi_created_667595_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="failedloginattempt",
            index=models.Index(
                fields=["username", "-created_at"],
                name="failed_logi_usernam_3f2a83_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="failedloginattempt",
            index=models.Index(
                fields=["resolved", "-created_at"],
                name="failed_logi_resolve_3ff0f8_idx",
            ),
        ),
    ]
