# Generated by Django 5.2 on 2025-11-13 00:58

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="FinancialLesson",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now, editable=False
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("title", models.CharField(help_text="Lesson title", max_length=255)),
                (
                    "content",
                    models.TextField(help_text="Lesson content (supports markdown)"),
                ),
                (
                    "age_group",
                    models.CharField(
                        choices=[
                            ("child", "Child (5-12)"),
                            ("teen", "Teen (13-17)"),
                            ("young_adult", "Young Adult (18-25)"),
                            ("adult", "Adult (26+)"),
                            ("all", "All Ages"),
                        ],
                        default="all",
                        help_text="Target age group for this lesson",
                        max_length=20,
                    ),
                ),
                (
                    "difficulty",
                    models.CharField(
                        choices=[
                            ("beginner", "Beginner"),
                            ("intermediate", "Intermediate"),
                            ("advanced", "Advanced"),
                        ],
                        default="beginner",
                        help_text="Lesson difficulty level",
                        max_length=20,
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        blank=True,
                        help_text="Lesson category (e.g., 'Budgeting', 'Saving', 'Investing')",
                        max_length=100,
                    ),
                ),
                (
                    "display_order",
                    models.PositiveIntegerField(
                        default=0, help_text="Order for displaying lessons"
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        blank=True,
                        help_text="Optional lesson image",
                        null=True,
                        upload_to="lessons/images/",
                    ),
                ),
                (
                    "video_url",
                    models.URLField(
                        blank=True,
                        help_text="Optional video URL (YouTube, Vimeo, etc.)",
                    ),
                ),
                (
                    "estimated_duration",
                    models.PositiveIntegerField(
                        default=5, help_text="Estimated minutes to complete lesson"
                    ),
                ),
                (
                    "is_published",
                    models.BooleanField(
                        default=False,
                        help_text="Whether this lesson is published and visible",
                    ),
                ),
                (
                    "summary",
                    models.TextField(
                        blank=True, help_text="Short summary for lesson preview"
                    ),
                ),
                (
                    "tags",
                    models.CharField(
                        blank=True,
                        help_text="Comma-separated tags for search",
                        max_length=255,
                    ),
                ),
            ],
            options={
                "verbose_name": "Financial Lesson",
                "verbose_name_plural": "Financial Lessons",
                "db_table": "financial_lessons",
                "ordering": ["display_order", "title"],
                "indexes": [
                    models.Index(
                        fields=["age_group", "is_published"],
                        name="financial_l_age_gro_a979ee_idx",
                    ),
                    models.Index(
                        fields=["category", "display_order"],
                        name="financial_l_categor_73e2b3_idx",
                    ),
                    models.Index(
                        fields=["is_published", "display_order"],
                        name="financial_l_is_publ_babf49_idx",
                    ),
                ],
            },
        ),
    ]
