# Generated by Django 5.2 on 2025-11-13 00:58

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Goal",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now, editable=False
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "name",
                    models.CharField(
                        help_text="Goal name (e.g., 'Holiday Fund', 'Emergency Fund')",
                        max_length=255,
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        help_text="Optional detailed description of the goal",
                    ),
                ),
                (
                    "goal_type",
                    models.CharField(
                        choices=[
                            ("savings", "Savings Goal"),
                            ("debt_payoff", "Debt Payoff"),
                            ("purchase", "Purchase Goal"),
                            ("emergency_fund", "Emergency Fund"),
                            ("investment", "Investment Goal"),
                            ("other", "Other"),
                        ],
                        default="savings",
                        help_text="Type of goal",
                        max_length=20,
                    ),
                ),
                (
                    "target_amount",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Target amount to reach",
                        max_digits=12,
                    ),
                ),
                (
                    "current_amount",
                    models.DecimalField(
                        decimal_places=2,
                        default=0.0,
                        help_text="Current progress towards goal (updated via service)",
                        max_digits=12,
                    ),
                ),
                ("due_date", models.DateField(help_text="Target completion date")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("completed", "Completed"),
                            ("paused", "Paused"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="active",
                        help_text="Current goal status",
                        max_length=20,
                    ),
                ),
                (
                    "milestone_amount",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Amount per milestone (e.g., $500 earns a sticker)",
                        max_digits=12,
                        null=True,
                    ),
                ),
                (
                    "sticker_count",
                    models.PositiveIntegerField(
                        default=0, help_text="Number of stickers/milestones earned"
                    ),
                ),
                (
                    "auto_contribute",
                    models.BooleanField(
                        default=False,
                        help_text="Whether to auto-contribute from transactions",
                    ),
                ),
                (
                    "contribution_percentage",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Percentage of income to auto-contribute (if enabled)",
                        max_digits=5,
                        null=True,
                    ),
                ),
                (
                    "icon",
                    models.CharField(
                        blank=True,
                        help_text="Icon or emoji for goal display",
                        max_length=50,
                    ),
                ),
                (
                    "color",
                    models.CharField(
                        default="#10B981",
                        help_text="Hex color for UI display",
                        max_length=7,
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        blank=True,
                        help_text="Optional image for goal visualization",
                        null=True,
                        upload_to="goals/%Y/%m/",
                    ),
                ),
            ],
            options={
                "verbose_name": "Goal",
                "verbose_name_plural": "Goals",
                "db_table": "goals",
                "ordering": ["due_date", "name"],
            },
        ),
        migrations.CreateModel(
            name="GoalProgress",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now, editable=False
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "amount_added",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Amount added to goal in this contribution",
                        max_digits=12,
                    ),
                ),
                (
                    "date_added",
                    models.DateTimeField(
                        default=django.utils.timezone.now,
                        help_text="When this contribution was made",
                    ),
                ),
                (
                    "notes",
                    models.TextField(
                        blank=True, help_text="Optional notes about this contribution"
                    ),
                ),
                (
                    "milestone_reached",
                    models.BooleanField(
                        default=False,
                        help_text="Whether this contribution triggered a milestone/sticker",
                    ),
                ),
            ],
            options={
                "verbose_name": "Goal Progress",
                "verbose_name_plural": "Goal Progress Records",
                "db_table": "goal_progress",
                "ordering": ["-date_added"],
            },
        ),
    ]
