# Generated by Django 5.2 on 2025-11-17 01:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("goals", "0001_initial"),
        ("households", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="goal",
            name="household",
            field=models.ForeignKey(
                help_text="Household this goal belongs to",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="goals",
                to="households.household",
            ),
        ),
        migrations.AddField(
            model_name="goalprogress",
            name="goal",
            field=models.ForeignKey(
                help_text="Goal this progress record belongs to",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="progress_records",
                to="goals.goal",
            ),
        ),
    ]
