# Generated by Django 5.2 on 2025-11-17 01:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("goals", "0002_initial"),
        ("transactions", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="goalprogress",
            name="transaction",
            field=models.ForeignKey(
                blank=True,
                help_text="Optional linked transaction for this contribution",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="goal_progress",
                to="transactions.transaction",
            ),
        ),
        migrations.AddIndex(
            model_name="goal",
            index=models.Index(
                fields=["household", "status"], name="goals_househo_ae538a_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="goal",
            index=models.Index(
                fields=["household", "due_date"], name="goals_househo_734282_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="goal",
            index=models.Index(
                fields=["status", "due_date"], name="goals_status_f69ce2_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="goalprogress",
            index=models.Index(
                fields=["goal", "date_added"], name="goal_progre_goal_id_e84c7f_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="goalprogress",
            index=models.Index(
                fields=["date_added"], name="goal_progre_date_ad_f77dd9_idx"
            ),
        ),
    ]
