# Generated by Django 5.2 on 2025-11-17 01:20

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Organisation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now, editable=False
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "name",
                    models.CharField(help_text="Organisation name", max_length=255),
                ),
                (
                    "organisation_type",
                    models.CharField(
                        choices=[
                            ("corp", "Corporation"),
                            ("npo", "Non-Profit Organisation"),
                            ("edu", "Educational Institution"),
                            ("gov", "Government Agency"),
                            ("club", "Club/Community Group"),
                            ("other", "Other"),
                        ],
                        default="corp",
                        help_text="Type of organisation",
                        max_length=10,
                    ),
                ),
                (
                    "contact_email",
                    models.EmailField(
                        help_text="Primary contact email for organisation",
                        max_length=254,
                    ),
                ),
                (
                    "phone_number",
                    models.CharField(
                        blank=True,
                        help_text="Organisation contact phone",
                        max_length=17,
                    ),
                ),
                ("address", models.TextField(blank=True, help_text="Physical address")),
                (
                    "website",
                    models.URLField(blank=True, help_text="Organisation website"),
                ),
                (
                    "default_budget_cycle",
                    models.CharField(
                        choices=[("m", "Monthly"), ("q", "Quarterly"), ("y", "Yearly")],
                        default="m",
                        help_text="Default budget cycle for organisation",
                        max_length=1,
                    ),
                ),
                (
                    "currency",
                    models.CharField(
                        choices=[
                            ("NZD", "New Zealand Dollar"),
                            ("AUD", "Australian Dollar"),
                            ("USD", "US Dollar"),
                            ("GBP", "British Pound"),
                            ("EUR", "Euro"),
                        ],
                        default="NZD",
                        help_text="Primary currency for organisation",
                        max_length=3,
                    ),
                ),
                (
                    "financial_year_start",
                    models.CharField(
                        default="01-01",
                        help_text="Financial year start (MM-DD format, e.g., '04-01' for April 1st)",
                        max_length=5,
                    ),
                ),
                (
                    "subscription_tier",
                    models.CharField(
                        choices=[
                            ("ww_starter", "Whānau Works Starter"),
                            ("ww_growth", "Whānau Works Growth"),
                            ("ww_enterprise", "Whānau Works Enterprise"),
                        ],
                        default="ww_starter",
                        help_text="Organisation subscription tier",
                        max_length=20,
                    ),
                ),
                (
                    "billing_cycle",
                    models.CharField(
                        choices=[("m", "Monthly"), ("q", "Quarterly"), ("y", "Yearly")],
                        default="m",
                        help_text="How often organisation is billed",
                        max_length=1,
                    ),
                ),
                (
                    "next_billing_date",
                    models.DateField(
                        blank=True, help_text="Next payment due date", null=True
                    ),
                ),
                (
                    "subscription_amount",
                    models.DecimalField(
                        decimal_places=2,
                        default=0.0,
                        help_text="Amount charged per billing cycle",
                        max_digits=10,
                    ),
                ),
                (
                    "payment_status",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("trial", "Trial Period"),
                            ("suspended", "Suspended"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="trial",
                        help_text="Current payment status",
                        max_length=20,
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True, help_text="Whether organisation account is active"
                    ),
                ),
                (
                    "max_members",
                    models.PositiveIntegerField(
                        default=50, help_text="Maximum number of members allowed"
                    ),
                ),
            ],
            options={
                "verbose_name": "Organisation",
                "verbose_name_plural": "Organisations",
                "db_table": "organisations",
            },
        ),
    ]
