# Generated by Django 5.2 on 2025-11-17 01:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("organisations", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="organisation",
            name="owner",
            field=models.ForeignKey(
                help_text="Organisation owner (billing/legal contact)",
                on_delete=django.db.models.deletion.PROTECT,
                related_name="owned_organisations",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddIndex(
            model_name="organisation",
            index=models.Index(fields=["name"], name="organisatio_name_9692c0_idx"),
        ),
        migrations.AddIndex(
            model_name="organisation",
            index=models.Index(
                fields=["is_active", "payment_status"],
                name="organisatio_is_acti_cd7dce_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="organisation",
            index=models.Index(fields=["owner"], name="organisatio_owner_i_ba2c26_idx"),
        ),
    ]
